# Generated by Django 5.0.14 on 2026-06-19 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0009_campaign_cached_counters'),
        ('campaigns', '0009_campaignlead_bounce_metadata'),
    ]

    operations = [
    ]
